### PR TITLE
Fixes bug with "this" context

### PR DESCRIPTION
**Pull request by ctaschereau**
Without this fix, the "this" keywords refers to the "createClient" function instead of the "client" defined at line 16.

### CODE REVIEW

**Comment by silverwind** [comment]
Hmm, I don't see how `this` could refer to anything meaningful before or after, assuming the event handler is not bound to the instance. Assuming you can test this, can you try setting `winner = client`?

**Comment by ctaschereau** [comment]
I can confirm that setting winner = client is in fact also correct. The "this" keyword refers to nothing useful when using arrow functions since there is no encapsulating function. When using the classic "function", "this" refers to the event handler (the client).

**Comment by silverwind** [comment]
If a arrow function is used, `this` should refer to the `forEach` body function, which also should be wrong, so please test and change the PR to `winner = client`.

**Comment by ctaschereau** [comment]
@silverwind I have updated the pull request with the `winner = client` code

**Comment by silverwind** [comment]
Thanks, I'll push a patch release with this.

BTW, I see that ldapjs is broken again on macOS 10.14 unless one deletes the dtrace-provider dependency. Might wanna check out https://github.com/zont/ldapjs-client which seems like a maintained alternative to ldapjs. I suppose support for multiple servers there could be contributed.

**Pull request merged**
